### ISSUE TITLE
Small erasing (same colour as background) line glitch when scrolling BLE MAC

### ISSUE THREAD

**Issue by dglaude** [virtualabs/hackwatch#36] opened 2022-08-30 16:05 UTC
When in "BLE Devices" with a lot of MAC, there is the option to scroll up.
However, scrolling up make an erasing line visible on top of the text "BLE Devices".
The line start from the middle of the "B" until the end on the right.
The line scroll at the same speed as the list of MAC.
It could be an invisible separator between MACs, that somehow goes outside of the bounding box?
I'll try attaching a picture.

**Comment by virtualabs** [comment] 2022-08-30 22:52
Fixed by commit f34781f940c386363b3e76c2b39cc56a208a63c4. Problem was caused by a wrong height when drawing list item background.

**Closed as completed by virtualabs** 2022-08-30 22:52 UTC
Labels: bug
