### ISSUE TITLE
UI2: Visual Glitch in "Rogue AP" AP selection screen

### ISSUE THREAD

**Issue by dglaude** [virtualabs/hackwatch#39] opened 2022-08-31 10:31 UTC
In AP selection from "Rogue AP" there are visual glitch:
* The white border is missing from the right of the screen and a bleu line is visible instate.
* The blue line is not complete and interrupted at the top, where the elevator is present.
(a picture would be best)

**Comment by virtualabs** [comment] 2022-08-31 14:30
I see what you mean, also the buttons are not correctly drawn (left vertical line of the button is drawn one pixel off). Definitely need to adjust some controls drawing routine (or figure out why vertical lines are not drawn correctly maybe).

**Comment by virtualabs** [comment] 2022-09-06 22:08
Bug is now fixed in commit acf6c3290df98eb7bc52c17fae823cf02fb03155, it was caused by a bug in `twatch-lib` introduced when I reworked the main screen driver (ST7789).

**Closed as completed by virtualabs** 2022-09-06 22:08 UTC
Labels: bug
